/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as SigninImport } from './routes/signin'
import { Route as MainImport } from './routes/_main'
import { Route as IndexImport } from './routes/index'
import { Route as MainGoalsNewImport } from './routes/_main.goals.new'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const MainGoalsLazyImport = createFileRoute('/_main/goals')()
const MainGoalsIdLazyImport = createFileRoute('/_main/goals/$id')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))

const SigninRoute = SigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signin.lazy').then((d) => d.Route))

const MainRoute = MainImport.update({
  id: '/_main',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/_main.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const MainGoalsLazyRoute = MainGoalsLazyImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => MainRoute,
} as any).lazy(() => import('./routes/_main.goals.lazy').then((d) => d.Route))

const MainGoalsIdLazyRoute = MainGoalsIdLazyImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MainGoalsLazyRoute,
} as any).lazy(() =>
  import('./routes/_main.goals.$id.lazy').then((d) => d.Route),
)

const MainGoalsNewRoute = MainGoalsNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MainGoalsLazyRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/_main/goals': {
      id: '/_main/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof MainGoalsLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/goals/new': {
      id: '/_main/goals/new'
      path: '/new'
      fullPath: '/goals/new'
      preLoaderRoute: typeof MainGoalsNewImport
      parentRoute: typeof MainGoalsLazyImport
    }
    '/_main/goals/$id': {
      id: '/_main/goals/$id'
      path: '/$id'
      fullPath: '/goals/$id'
      preLoaderRoute: typeof MainGoalsIdLazyImport
      parentRoute: typeof MainGoalsLazyImport
    }
  }
}

// Create and export the route tree

interface MainGoalsLazyRouteChildren {
  MainGoalsNewRoute: typeof MainGoalsNewRoute
  MainGoalsIdLazyRoute: typeof MainGoalsIdLazyRoute
}

const MainGoalsLazyRouteChildren: MainGoalsLazyRouteChildren = {
  MainGoalsNewRoute: MainGoalsNewRoute,
  MainGoalsIdLazyRoute: MainGoalsIdLazyRoute,
}

const MainGoalsLazyRouteWithChildren = MainGoalsLazyRoute._addFileChildren(
  MainGoalsLazyRouteChildren,
)

interface MainRouteChildren {
  MainGoalsLazyRoute: typeof MainGoalsLazyRouteWithChildren
}

const MainRouteChildren: MainRouteChildren = {
  MainGoalsLazyRoute: MainGoalsLazyRouteWithChildren,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof MainRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/about': typeof AboutLazyRoute
  '/goals': typeof MainGoalsLazyRouteWithChildren
  '/goals/new': typeof MainGoalsNewRoute
  '/goals/$id': typeof MainGoalsIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof MainRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/about': typeof AboutLazyRoute
  '/goals': typeof MainGoalsLazyRouteWithChildren
  '/goals/new': typeof MainGoalsNewRoute
  '/goals/$id': typeof MainGoalsIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_main': typeof MainRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/about': typeof AboutLazyRoute
  '/_main/goals': typeof MainGoalsLazyRouteWithChildren
  '/_main/goals/new': typeof MainGoalsNewRoute
  '/_main/goals/$id': typeof MainGoalsIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/signin'
    | '/signup'
    | '/about'
    | '/goals'
    | '/goals/new'
    | '/goals/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/signin'
    | '/signup'
    | '/about'
    | '/goals'
    | '/goals/new'
    | '/goals/$id'
  id:
    | '__root__'
    | '/'
    | '/_main'
    | '/signin'
    | '/signup'
    | '/about'
    | '/_main/goals'
    | '/_main/goals/new'
    | '/_main/goals/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRoute: typeof MainRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  AboutLazyRoute: typeof AboutLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRoute: MainRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  AboutLazyRoute: AboutLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_main",
        "/signin",
        "/signup",
        "/about"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_main": {
      "filePath": "_main.tsx",
      "children": [
        "/_main/goals"
      ]
    },
    "/signin": {
      "filePath": "signin.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/_main/goals": {
      "filePath": "_main.goals.lazy.tsx",
      "parent": "/_main",
      "children": [
        "/_main/goals/new",
        "/_main/goals/$id"
      ]
    },
    "/_main/goals/new": {
      "filePath": "_main.goals.new.tsx",
      "parent": "/_main/goals"
    },
    "/_main/goals/$id": {
      "filePath": "_main.goals.$id.lazy.tsx",
      "parent": "/_main/goals"
    }
  }
}
ROUTE_MANIFEST_END */
