/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const MainLazyImport = createFileRoute('/_main')()
const IndexLazyImport = createFileRoute('/')()
const MainGoalsLazyImport = createFileRoute('/_main/goals')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const MainLazyRoute = MainLazyImport.update({
  id: '/_main',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/_main.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const MainGoalsLazyRoute = MainGoalsLazyImport.update({
  path: '/goals',
  getParentRoute: () => MainLazyRoute,
} as any).lazy(() => import('./routes/_main.goals.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/_main/goals': {
      id: '/_main/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof MainGoalsLazyImport
      parentRoute: typeof MainLazyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  MainLazyRoute: MainLazyRoute.addChildren({ MainGoalsLazyRoute }),
  AboutLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_main",
        "/about"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_main": {
      "filePath": "_main.lazy.tsx",
      "children": [
        "/_main/goals"
      ]
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/_main/goals": {
      "filePath": "_main.goals.lazy.tsx",
      "parent": "/_main"
    }
  }
}
ROUTE_MANIFEST_END */
