name: Create Release

on:
  workflow_call:

jobs:
  release:
    name: Bump Version, Create Changelog & GitHub Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_annotated_tag: true

      - run: echo "Changelog ${{ steps.tag_version.outputs.changelog }}"

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          fromTag: ${{ steps.tag_version.outputs.previous_tag }}
          toTag: ${{ steps.tag_version.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\\n\\n[Full Changelog](#{{RELEASE_DIFF}})",
              "pr_template": "- #{{TITLE}} (##{{NUMBER}})",
              "categories": [
                { "title": "## Features", "labels": ["feat"] },
                { "title": "## Bug Fixes", "labels": ["fix"] },
                { "title": "## Performance Improvements", "labels": ["perf"] },
                { "title": "## Code Refactoring", "labels": ["refactor"] },
                { "title": "## Tests", "labels": ["test", "tests"] },
                { "title": "## Build System", "labels": ["build"] },
                { "title": "## Continuous Integration", "labels": ["ci"] },
                { "title": "## Documentation", "labels": ["docs"] },
                { "title": "## Styling", "labels": ["style"] },
                { "title": "## Reverts", "labels": ["revert"] },
                { "title": "## Other", "labels": ["chore", "other"] }
              ],
              "label_extractor": [
                {
                  "pattern": "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                  "on_property": "title",
                  "target": "$1"
                }
              ]
            }

      - run: echo "${{ steps.build_changelog.outputs.changelog }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.build_changelog.outputs.changelog }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
