name: Deploy Web

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Cloudflare Pages & Create Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      deployments: write

    environment: Production – seongoals

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Web App for Production
        run: pnpm --filter web build
        env:
          VITE_CDN_URL: ${{ vars.VITE_CDN_URL || secrets.VITE_CDN_URL }}
          SENTRY_AUTH_TOKEN: ${{ vars.SENTRY_AUTH_TOKEN || secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_DSN: ${{ vars.SENTRY_DSN || secrets.SENTRY_DSN }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT || secrets.SENTRY_PROJECT }}
        #   VITE_IS_DEMO: ${{ vars.VITE_IS_DEMO || secrets.VITE_IS_DEMO }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: packages/web
          command: pages deploy dist --project-name=${{vars.CLOUDFLARE_PAGES_PROJECT_NAME}} --commit-dirty=true
          packageManager: pnpm
        #   gitHubToken: ${{ secrets.GITHUB_TOKEN }}
