name: Web E2E Test

on:
  push:
    branches:
      - main
    paths:
      - 'packages/web/**'
      - 'playwright.config.ts'
      - '.github/workflows/web-deploy.yml'
      - 'pnpm-workspace.yaml'
      - 'package.json'
      - 'pnpm-lock.yaml'
  workflow_dispatch:

jobs:
  test:
    name: Run Web E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: Test - seon-web
    container:
      image: mcr.microsoft.com/playwright:v1.52.0
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build Web App
        run: pnpm --filter seon-web build
        env:
          VITE_SUPABASE_URL: ${{ vars.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ vars.VITE_SUPABASE_ANON_KEY }}
          VITE_POWERSYNC_URL: ${{ vars.VITE_POWERSYNC_URL }}
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          VITE_CDN_URL: ${{ vars.VITE_CDN_URL }}
          VITE_IS_DEMO: ${{ vars.VITE_IS_DEMO }}

      - name: Run Playwright tests
        run: pnpm --filter seon-web exec playwright test
        env:
          HOME: /root

      - name: Upload Playwright Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: packages/web/playwright-report/
          retention-days: 30
